# Generated by Django 3.2 on 2023-09-14 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'ordering': ('-author_id',), 'verbose_name': 'Подписка'},
        ),
    ]
